name = "claudineandmarkgallery"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[[d1_databases]]
binding      = "DB"
database_name = "wedding-gallery-social"
database_id   = "632f409e-5fda-481b-862a-9506cb176559"
